AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for creating an EventBridge API Destination with an API Key.
Parameters:
  MomentoAuthToken:
    Type: String
Mappings:
  RegionToEndPoint:
    us-east-1:
      URL: https://api.cache.cell-us-east-1-1.prod.a.momentohq.com
    us-west-2:
      URL: https://api.cache.cell-4-us-west-2-1.prod.a.momentohq.com
    ap-south-1:
      URL: https://api.cache.cell-1-ap-south-1-1.prod.a.momentohq.com
    ap-northeast-1:
      URL: https://api.cache.cell-ap-northeast-1-1.prod.a.momentohq.com
    eu-west-1:
      URL: https://api.cache.cell-1-eu-west-1-1.prod.a.momentohq.com
Resources:
  ApiDestinationsTargetRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Path: /service-role/
      Policies:
        - PolicyName: destinationinvoke
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - events:InvokeApiDestination
                Resource:
                  - Fn::GetAtt:
                      - MomentoApiCachePut
                      - Arn
                  - Fn::GetAtt:
                      - MomentoApiCacheDelete
                      - Arn
                  - Fn::GetAtt:
                      - MomentoApiTopicsPost
                      - Arn
  FailedDeliveryDLQ:
    Type: AWS::SQS::Queue
  ApiConnection:
    Type: AWS::Events::Connection
    Properties:
      AuthorizationType: API_KEY
      AuthParameters:
        ApiKeyAuthParameters:
          ApiKeyName: Authorization
          ApiKeyValue:
            Fn::Sub: ${MomentoAuthToken}
  MomentoApiCachePut:
    Type: AWS::Events::ApiDestination
    Properties:
      ConnectionArn:
        Fn::GetAtt:
          - ApiConnection
          - Arn
      HttpMethod: PUT
      InvocationEndpoint:
        Fn::Sub:
          - ${RegionEndpoint}/cache/*
          - RegionEndpoint:
              Fn::FindInMap:
                - RegionToEndPoint
                - Ref: AWS::Region
                - URL
      InvocationRateLimitPerSecond: 300
  MomentoApiCachePutRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: default
      EventPattern:
        detail-type:
          - cacheSet
      State: ENABLED
      Targets:
        - Id: cacheSet-rule
          Arn:
            Fn::GetAtt:
              - MomentoApiCachePut
              - Arn
          RoleArn:
            Fn::GetAtt:
              - ApiDestinationsTargetRole
              - Arn
          InputTransformer:
            InputPathsMap:
              message: $.detail.message
            InputTemplate: '"<message>"'
          HttpParameters:
            PathParameterValues:
              - $.detail.cacheName
  MomentoApiCacheDelete:
    Type: AWS::Events::ApiDestination
    Properties:
      ConnectionArn:
        Fn::GetAtt:
          - ApiConnection
          - Arn
      HttpMethod: DELETE
      InvocationEndpoint:
        Fn::Sub:
          - ${RegionEndpoint}/cache/*
          - RegionEndpoint:
              Fn::FindInMap:
                - RegionToEndPoint
                - Ref: AWS::Region
                - URL
      InvocationRateLimitPerSecond: 300
  MomentoApiCacheDeleteRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: default
      EventPattern:
        detail-type:
          - cacheDelete
      State: ENABLED
      Targets:
        - Id: cacheDelete-rule
          Arn:
            Fn::GetAtt:
              - MomentoApiCacheDelete
              - Arn
          RoleArn:
            Fn::GetAtt:
              - ApiDestinationsTargetRole
              - Arn
          HttpParameters:
            PathParameterValues:
              - $.detail.cacheName
  MomentoApiTopicsPost:
    Type: AWS::Events::ApiDestination
    Properties:
      ConnectionArn:
        Fn::GetAtt:
          - ApiConnection
          - Arn
      HttpMethod: POST
      InvocationEndpoint:
        Fn::Sub:
          - ${RegionEndpoint}/topics/*/*
          - RegionEndpoint:
              Fn::FindInMap:
                - RegionToEndPoint
                - Ref: AWS::Region
                - URL
      InvocationRateLimitPerSecond: 300
  MomentoApiTopicsPostRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: default
      EventPattern:
        detail-type:
          - topicPublish
      State: ENABLED
      Targets:
        - Id: topicPublish-rule
          Arn:
            Fn::GetAtt:
              - MomentoApiTopicsPost
              - Arn
          RoleArn:
            Fn::GetAtt:
              - ApiDestinationsTargetRole
              - Arn
          InputTransformer:
            InputPathsMap:
              message: $.detail.message
            InputTemplate: '"<message>"'
          HttpParameters:
            PathParameterValues:
              - $.detail.cacheName
              - $.detail.topicName
